### ISSUE TITLE
尝试运行你的例子的时候出现了importError和attributeError

### ISSUE THREAD

**Issue by moonlightnoodles** [zejunwang1/gpt2ppl-zh#1]
when I run your example

**Comment by zejunwang1** [comment]
有具体错误信息吗，截图发出来看看

**Comment by moonlightnoodles** [comment]
<img width="783" alt="20230810171917" src="https://github.com/zejunwang1/gpt2ppl-zh/assets/123880310/5a233c43-112a-430d-a7a7-5e248243461d">

**Comment by moonlightnoodles** [comment]
感谢你的回复

**Comment by moonlightnoodles** [comment]
问题已经解决了（昨天出现的不是这个问题），还是感谢您的回复
